spring.application.name=Distributed-Application

# application.properties

# Path to the product data JSON file in the resources folder
# product.data.file=data.product.json

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=secret
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.thymeleaf.cache=false


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
app.currency.default=EUR

spring.main.allow-circular-references=true
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true



api.key=1234


